#!/bin/bash


# Debugging settings:
#####################
# exit immediately upon any error, output each line as it is executed
set -ex -o pipefail



# command looks like this
#-------------------------
# STAR2 --genome-dir GGG --readFilesIn /long/path/bla_R1_bla.tar.gz /long/path/bla_R1_bla.tar.gz bla_R1_bla.tar.gz  etc...
#  $0         $1      $2        $3           $4                                   $5                   $6               $7

# lets check it
echo "STAR2 command line"
echo ${@}

echo outFileNamePrefix precursors
echo $5



# figure out common part from both paired ends filenames, to define outFileNamePrefix parameter
#----------------------------------------------------------------------------------------------
OUTFILENAMEPREFIX=$5 # changed from using namemerge
echo $OUTFILENAMEPREFIX

# decompress the reference genome archive
#-----------------------------------------
mkdir genomedir
tar -C genomedir --strip-components=1 -xvf $2



# figure out if the input files are gzipped or not
#-------------------------------------------------
FILE1=${4}
#FILE2=${5}
ZCAT=""
if [[ $FILE1 = *.gz ]]
then
  ZCAT="--readFilesCommand zcat"
fi
echo $ZCAT

# TODO is this still useful ?
#tar -zxvf $FILE1
#tar -zxvf $FILE2
#$FILE1=${FILE1:0:-3}
#$FILE2=${FILE1:0:-3}
#STAR --genomeDir genomedir --readFilesIn $FILE1 $FILE2 $ZCATOPTION ${@:7}

# have a look at directory just before running star
# -------------------------------------------------
ls -l

# generate the real star command and run it
#------------------------------------------
FINALSTARCOMMAND="STAR $ZCAT --genomeDir genomedir --outFileNamePrefix ${OUTFILENAMEPREFIX}  $3  $4  ${@:6} > stdoutfile"  # TODO: more elegantly change from paired end to se
echo ${FINALSTARCOMMAND}
${FINALSTARCOMMAND}


# rename some of the outputs to match filename conventioms
#---------------------------------------------------------
ls -l
for filewithout in *.out* ; do mv $filewithout ${filewithout/.out/}; done
for filewithaligned in *.Aligned* ; do mv $filewithaligned ${filewithaligned/.Aligned/Ma}; done
for filewithunmapped in *.Unmapped.mate* ; do mv $filewithunmapped ${filewithunmapped/.Unmapped.mate/U}.fq; done
for filewithlogfinal in *.Log.final ; do mv $filewithlogfinal ${filewithlogfinal/.Log.final/Ma.metrics}; done
ls -l


